# Extract Word to Dataframe

In [1]:
from docx import Document
import pandas as pd
import os

In [ ]:
def extract_text(file_path):
    doc = Document(file_path)
    text = []
    for para in doc.paragraphs:
        text.append(para.text)
    return "\n".join(text)

# Read and process all .docx files in the specified folder
folder_path = "Resumes"
data = []
for filename in os.listdir(folder_path):
    if filename.endswith(".docx"):
        file_path = os.path.join(folder_path, filename)
        print(f"Processing: {filename}")
        
        try:
            text = extract_text(file_path)
            data.append({
                "filename": filename,
                "text": text
            })
        except Exception as e:
            print(f"  [ERROR] {filename}: {e}")

# Create a DataFrame and save to CSV
df = pd.DataFrame(data)
df["ID"] = df.index + 1
print(df.head())
print(f"Total: {len(df)} dokumen")

output_csv = "resumes_text.csv"
df.to_csv(output_csv, index=False)

Processing: Abiral_Pandey_Fullstack_Java.docx
Processing: Achyuth Resume_8.docx
Processing: Adelina_Erimia_PMP1.docx
Processing: Adhi Gopalam - SM.docx
Processing: AjayKumar.docx
Processing: Akhil.profile.docx
Processing: Akhil_Sr BSA.docx
Processing: Alekhya Resume.docx
Processing: Amar Sr BSA.docx
Processing: Ami Jape.docx
Processing: Amrinder Business Analyst.docx
Processing: Amulya Komatineni.docx
Processing: Anil Krishna Mogalaturthi.docx
Processing: AnilAgarwal.docx
Processing: Anudeep N_Sr Java Developer.docx
Processing: Ashok Jayakumar - PM.docx
Processing: Ashwini J2EE Developer.docx
Processing: Atul_Mathur_Resume.docx
Processing: Avathika BA-Healthcare_.docx
Processing: avinash G.docx
Processing: B Shaker-Sr BSA-Scrum Master .docx
Processing: B Suresh Kumar_Project Manager_1.docx
Processing: BA - Abhishek.docx
Processing: BA - Navneet.docx
Processing: BA Kiran.docx
Processing: BA with INV.docx
Processing: Balaji Gopalakrishnan Project Manager.docx
Processing: Balakrishna Sudabathula.docx
Processing: Bapuji Hadoop developer.docx
Processing: Bharat Arora_CV_PMP _ ERP1.docx
Processing: Bharatha BA Resume.docx
Processing: Brahma-Resume (BA).docx
Processing: Business Analyst_GHyma.docx
Processing: Chandler_BA.docx
Processing: chenna kesava.docx
Processing: CHETAN_Sr Java Developer.docx
Processing: Dantu Padmasri - Project Manager.docx
Processing: Dave.docx
Processing: Deepika Chintalapati.docx
Processing: Deepika DC.docx
Processing: Derik.docx
Processing: Dhanalaxmi -BA.docx
Processing: Drakshajavauidev.docx
Processing: employer_mounika details.docx
Processing: Francis Gomes Resume.docx
Processing: Gautami Bulusu Mobile Testing 3.docx
Processing: Gokul Selvam S PM.docx
Processing: Gopi.docx
Processing: Gururaja Murthy PMCPCSM.docx
Processing: Haarika_BA.docx
Processing: Harika_java.docx
Processing: Harish K.docx
Processing: harish S.docx
Processing: HARI_Sr.Java Developer.docx
Processing: Harshitha Challa.docx
Processing: indrakaran soma.docx
Processing: jagadeesh k.docx
Processing: Jagan S Iyer PM.docx
Processing: Jaya prakash.docx
Processing: Jayadattaperi N.docx
Processing: jeck P.docx
Processing: Jennifer  M. Conte.docx
Processing: Jimi_Desai_PM.docx
Processing: kalyan das.docx
Processing: Kashyap K. Vora resume.docx
Processing: KIRAN KUMAR.docx
Processing: komal patel.docx
Processing: Komala BSA Resume.docx
Processing: Krishna Kuruvella.docx
Processing: Krishna Sr. BSA Resume.docx
Processing: Krishnapriya_BA.docx
Processing: Krishna_BSA.docx
Processing: Krishna_SrJava.docx
Processing: Kumar Raj.docx
Processing: Kuppurajbabu_BA.docx
Processing: KY BA PM UPDATED RESUME .docx
Processing: Madhuri Pawar.docx
Processing: madhuri R.docx
Processing: madhuri_java.docx
Processing: mahesh_Java.docx
Processing: Mahesh_Kamath_PM (1).docx
Processing: Manikanta P.docx
Processing: manish_singh_resume.docx
Processing: Mani_Hadoop.docx
Processing: Manohar B.docx
Processing: Manohar Reddy.docx
Processing: manohar.B.docx
Processing: Mehul.docx
Processing: Mitali Barman_Resume.docx
Processing: Mohamad Jamil.docx
Processing: Mohammad Resume.docx
Processing: mohid_rj.docx
Processing: mounika BA resume 7.docx
Processing: Mounika health care resume.docx
Processing: MounikaReddy.docx
Processing: Mounika_P.docx
Processing: Nandini_Resume.docx
Processing: Naren Sr.BA .docx
Processing: Naren Sr.BA.docx
Processing: Naresh V.docx
Processing: Naveen Arora.docx
Processing: Naveen Kumar Bandela.docx
Processing: Naveen.S_Resume.docx
Processing: Navneeth Resume.docx
Processing: Neha Mugghala.docx
Processing: Nikhil.docx
Processing: Nikith Reddy.docx
Processing: Nikki_Nimmagadd.docx
Processing: Nilesh-resume_1_phplead.docx
Processing: Niteesh Java Developer.docx
Processing: nithin katapally.docx
Processing: nithin Reddy.docx
Processing: Othman - Project Manager.docx
Processing: Pankaj BSA.docx
Processing: ParthMPatel_BA.docx
Processing: Pavan Kumar Full Stack Java Developer.docx
Processing: Pavan Sr Business Analyst resume.docx
Processing: Pierre John.docx
Processing: PM RESUME.docx
Processing: Pranay P.docx
Processing: Prashant Chawda_resume.docx
Processing: Praveen B.docx
Processing: Praveen T.docx
Processing: Priya B.docx
Processing: Priyanka Sr BSA Resume.docx
Processing: Priya_Sharma.docx
Processing: Rajendra-PMP-CSM.docx
Processing: Rajesh_k.docx
Processing: Raju Goduguchinta_Technical Program Manager.docx
Processing: ram krishna.docx
Processing: ram nandyala.docx
Processing: Ramachandra EDA.docx
Processing: Ramteja Motupalli.docx
Processing: RAMYA BUSINESS ANALYST RESUME.docx
Processing: Randy Adams.docx
Processing: Ranjan_Project Manager-Scrum Master.docx
Processing: Rao_Java.docx
Processing: Rashmitha R.docx
Processing: Ravi Pattar- Sr. Agile Program manager.docx
Processing: Ravi Reddy.docx
Processing: RaviBurra_Certified PM_DevOps.docx
Processing: ravikiran JALASUTRAPU.docx
Processing: RaviRaju_Resume.docx
Processing: Reddemma_Lankipalle.docx
Processing: Resume - Kishore Kotapati - 218E - BA.docx
Processing: Resume - PM Agile-Scrum.docx
Processing: Resume - Sr PM.docx
Processing: Resume Vishal PM - MSIS, PMP-PMI.docx
Processing: Resume2018March.docx
Processing: Resume_Spoorti Pandit_BSA.docx
Processing: Robinson.docx
Processing: Rohanu Resume.docx
Processing: ronith s.docx
Processing: Sahas BA Resume.docx
Processing: Sahithi K.docx
Processing: sai k.docx
Processing: Sai Krishna BA.docx
Processing: Sai kumar.docx
Processing: Sai Srinivas_Sr_Java_Developer.docx
Processing: sairithvik alla.docx
Processing: Saiteja G.docx
Processing: Samir Naik-NJ - Feb 2018-V6.0.docx
Processing: Samir Naik-NJ - Mar 2018-V3.0.docx
Processing: sanjay kumar.docx
Processing: Santosh Arugula BA.docx
Processing: Sarath M.docx
Processing: SaravanaKumar.docx
Processing: Satish Reddy.docx
Processing: Satish Uduta.docx
Processing: SAURABH_PM.docx
Processing: Shail_Tank-Business Analyst .docx
Processing: Shaker Resume.docx
Processing: Sharath Java.docx
Processing: Shashank.docx
Processing: Shelly Woods.docx
Processing: Shiuli Mahmud.docx
Processing: Shiva G-Java Resume.docx
Processing: Siddhartha Gandroju.docx
Processing: Smita Kamble_Resume.docx
Processing: Sougandh_Java Fullstack Developer.docx
Processing: Spoorthi Finance BSA Resume.docx
Processing: Sr. Business Analyst.docx
Processing: Sravani Battu.docx
Processing: Sravani Singirikonda.docx
Processing: Sri Gati.docx
Processing: srinivas b.docx
Processing: Srivatsan_Project_Manager.docx
Processing: Sudhakar Reddy.docx
Processing: Sumanth Manne Java Developer.docx
Processing: Sundar_Java_8+ Years..docx
Processing: SUNITHA Project Manager (1).docx
Processing: Syed_Zia_Ashraf.docx
Processing: Tanmay_Dam_Resume_BA.docx
Processing: Tarun RESUME-BSAT.docx
Processing: Tarun Resume.docx
Processing: Tarun.docx
Processing: Tarun_Developer.docx
Processing: Tejaswi-resume.docx
Processing: Tushar Patel.docx
Processing: Uday_Maripelly.docx
Processing: Ujvala BA Feb 20.docx
Processing: Utthan Silawal12.docx
Processing: V Ashok A.docx
Processing: Vamshi L.docx
Processing: Vamshi Teja_Business Analyst.docx
Processing: Varun Kumar.docx
Processing: Varun.docx
Processing: vema reddy.docx
Processing: Venkata_Sr.PHP_Developer.docx
Processing: Venkat_BA.docx
Processing: venu b.docx
Processing: Vijay Bhargav.docx
Processing: VIJETHA G.docx
Processing: vikas java.docx
Processing: Vikash_BA_Ab.docx
Processing: Vinay.D_Resume.docx
Processing: Vishal S..docx
Processing: Vishnu BA Resume.docx
Processing: Vishnu J.docx
Processing: Vishnu Java dev.docx
Processing: Vivek Joshi_CV.docx
Processing: Vivek.BSA.docx
Processing: Yohan BSA.docx
Processing: Yugesh_Resume.docx
                            filename  \
0  Abiral_Pandey_Fullstack_Java.docx
1              Achyuth Resume_8.docx
2           Adelina_Erimia_PMP1.docx
3             Adhi Gopalam - SM.docx
4                     AjayKumar.docx

                                                text  ID
0  Name: Abiral Pandey\nEmail: abiral.pandey88@gm...   1
1  Achyuth\n540-999-8048\nachyuth.java88@gmail.co...   2
2  Adelina Erimia, PMP, Six Sigma Green Belt, SMC...   3
3  Adhi Gopalam\nadhigopalam@gmail.com\n281-212-3...   4
4  Ajay Kumar (CSM)\t     \t\t     Email/Skype: a...   5
Total: 224 dokumen

# EDA

In [3]:
df = pd.read_csv(output_csv)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   filename  224 non-null    object
 1   text      221 non-null    object
 2   ID        224 non-null    int64
dtypes: int64(1), object(2)
memory usage: 5.4+ KB

In [5]:
df.isnull().sum()

filename    0
text        3
ID          0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
print(df["text"][4])

Ajay Kumar (CSM)	     		     Email/Skype: ajaydt@gmail.com; Mob. +1 (847)899-4194
PROFESSIONAL SUMMARY:
14 Years IT experience as an Architect, Solutions, Scrum Master, Quality Assurance and Agile Practitioner (Agile Methodology - Healthcare) with SAFe (Scaled Agile Framework) including ETL Testing and Web Services, Selenium Automation engagement of Web application, Project management and technical team handling experience from 20+ associates. Extensive health care background with software implementation knowledge and extensive background in Retail, eCommerce, Point of Sale,  Banking & Finance, Cards & Payments, Government, Education projects.
Strong experience in Agile Testing concepts and Testing process, experience in managing complex issues and risks, including appropriate verbal and written.
Prepares and follows up on regular Scrum events; including daily scrum, sprint planning sessions, backlog grooming, retrospectives. Facilitation and coordination of Agile Program Increment (PI) planning.
Uses metrics to track and review team performance including Burn-down charts, velocity, and other sprint and release metrics.
Promoting continuous improvement to increase team effectiveness and helping the organization and key stakeholders in adapting an Agile mindset.
Experience working with Product Owners, architecture, technical leads and other stakeholders to manage cross team and their dependencies.
Expertise in Test Governance & Test process compliance, vast experience working in a client and business facing role.
Create test plans, traceability matrices and test impact analysis documents.
Design and develop test cases using industry best practices; report defects utilizing industry standard defect tracking tools.
Excellent knowledge in testing metrics and ability to utilize them in day to day testing activities.
Review complex software requirements and uncover requirements defects.
Specialized in web and E-commerce testing, test automation scripts using Selenium and Java.
Advanced experience of various phases of Software Development Life Cycle (SDLC) while understanding the role of tester in each phase.
Quality Plan documentation, involved in Project planning documentation included budgeting, staffing profiles, project timelines, issue tracking, and dependency tracking.
Excellent analytical, problem solving, troubleshooting skills and Well acquainted with the SDLC, Agile and STLC.
Expertise in HP ALM, Rally, Jira, Bugzilla, Selenium Web Driver, TestNG, SOAP UI, REST, WinSCP, ETL, Putty, SQL Developer tools for current project.
Experience in Release Management lifecycle and deploy releases into production which includes scheduling, coordinating and the management of releases across the enterprise for multiple Applications Updates, Hotfixes, Security Improvements, Operating System updates.
Advanced technical knowledge including an understanding of Continuous Integration tools used as Jenkins to achieve efficient and fast delivery and accelerate time to value and even revenue.
Expert in leading the validation of multiple complex interfaces with broad knowledge of Integration Testing (creating and executing test cases at the Unit/ Integration/ System level/UAT), Automated Testing (Web Testing, GUI, Client Server) and Field Validation (Client-side, Server-side and ETL database).
Experience in meeting tight timelines and delivery quality work to customer including reviewing cross discipline deliverables.
Extensive elicitation abilities through SWOT Analysis, Surveys and well facilitated JAD sessions to understand the As-Is business model to gather User and Business Requirements.
Excellent organizational and presentation skills in directing the To-Be model of the business through proper GAP Analysis in order to generate the necessary Business Requirements Document (BRD), System Requirements Specification (SRS), Functional Requirements Document (FRD), Change Request Processes (CRP), and Contingency Planning (CP). Knowledge and experience working on smoke testing, debugging.
Experience in data mining, data analysis, data manipulation, database statistics, Data warehousing.
Excellent verbal and communication skills necessary to elicit requirements through observation, surveys, interviews, Joint Application Development (JAD) sessions and Brainstorming with Business Owners, Business Users, SMEs and other stakeholders.
Experience implementing Unified Modeling Language (UML) and MS VISIO in creating Use Cases, Sequence Diagrams, Collaboration Diagrams, Activity Diagrams and Class Diagrams.
Change Request Management experience including industry standard CRM tools.
Experience in creating WBS (Work Breakdown Structure) with dependencies and project stakeholders using MS Project.
Experience in tracing requirements throughout the development process and verifying adherence to Requirement Traceability Matrix (RTM).
Significant experience in reviewing Test Procedures, creating Test Cases and conducting User Acceptance Testing (UAT).
Role includes: Technical guidance’s to the team, Web Testing, Database Testing, Automation, Business Intelligence, project monitoring and control, resource allocation, drafting project proposals, effort estimations, schedule, project report and status, training, managing interview drives /conduct, onsite-offshore coordination.

TECHNICAL SKILL-SET:
Management Tools	    	: 	MS Projects, Visio, Office, SharePoint, Rally, Jira, PlanView
Methodologies	    	: 	Agile and Scrum Model, Waterfall, V Model
Functional Tool	    	: 	Selenium, HP UFT, QTP, Winrunner, Rational Robot, SOAP/REST
Performance Tool	    	: 	JMeter, SQL Query Analyzer, Dynatrace
Defect Mgmt. Tool	    	: 	Rally, Bugzilla, Jira, Rational Clear Quest, TIR
Test Mgmt. Tool	    	: 	HP ALM, Quality Center, Test Director
Database		    	: 	Oracle, SQL-Server, Infosphere DataStage, ETL, QMF, Squirrel
Languages Conscious 	: 	C++ (OOP Concept), Unix, VB Script, Java Script, WSDL, XML
Configuration Tools	    	: 	GIT, GitHub Extension, SVN, CVS, VSS, Mindshare, SharePoint
Other Tools		    	: 	Putty, WinScp, SOA, Junit, TestNG, POM, AutoPilot for MQ
Operating System	    	: 	Windows/XP professional, Citrix Metaframe Server, Unix

PROFESSIONAL EXPERIENCE:
UHG (Optum Insight), MN, USA - Oct 2015 to Till Date
Scrum Master, QA Lead – Agile/Scrum/PM/QA - Care Manager (http://caremanager.optum.com)
Technologies: Java, Rally, ALM, ETL Datastage Director, SQL Developer, SharePoint, Jenkins, Git, JIRA, Selenium, TestNG, MS Visio and Office, SOAP/REST, Swagger, AutoPilot, WinSCP, Putty, Beyond Compare
Role and Responsibilities:
Acted as the primary point of contact for the design team in all development meetings which strengthened work alignment between development and design teams
Developed and maintain the design team's product backlog and roadmap improving team organization and clearly defines sprint goals
Responsible for managing global project teams and supporting Optum in their Agile transformation. Facilitating workshops with multiple stakeholders, development and support teams to create a common understanding of project objectives, features and user stories,  sprint planning, tracking, removing impediments, communications and backlog grooming.
Planned sprint priorities with Product Owners & Product Managers to ensure proper design requirements are consistently met.
Facilitated scrum meetings and encouraged team collaboration to enable design team to achieve sprint goals & deliverables.
Aided our Product Manager & Product Owner by created and maintaining a competitive analysis of similar products throughout the business intelligence/data analytics industry.
Removed impediments and combated evolving requirements by implementing a workflow oriented process to better represent proper scope of stories while working with cross functional teams.
Handled scrum team consist of cross trained resources in Java , ETL resources and BI tools .
Involved on effective testing strategies to provide Quality Assurance and developed test cases.
Managing software development life cycle (SDLC) for Java, J2EE Projects including analysis, design, testing and implementation of software applications.
Source code and version control management with Git, Github extension and SharePoint.
Lead the daily scrum calls with offshore teams situated in different time zones to monitor the progress of the deliverables.
Guiding the team to produce quality software on a predictable schedule using Agile/Scrum principles and practices.
Coach teams through Scrum ceremonies, including: Sprint Planning, Backlog Refinement, Sprint Demo, Sprint Retrospective, and Daily Stand-up.
Facilitating and following up on actions for all Scrum ceremonies including grooming, planning, stand-ups, reviews and retrospectives.
Creating and maintaining information radiators that track progress at multiple levels, including following up with the team to ensure daily updates.
Removing impediments to team progress either directly or by finding the right personnel to remove the impediment.
Building a trusting and safe environment where problems can be raised without fear of blame, retribution, or being judged, with an emphasis of healing and problem solving.
Facilitating discussion, decision making, and conflict resolution.
Helping the team to continually evolve the process, seeking improvements and greater efficiency.
Assisting with internal and external communication, improving transparency, and radiating information.
Supporting and educating the Product Owner, especially with respect to grooming and maintaining the product backlog.
Provide process and tool training and coaching for new projects and new team members.
Providing all support to the team using a servant leadership style whenever possible, and leading by example.
Implementing SAFe inorder to Visualize and limit WIP, reduce batch sizes and manage queue lengths.
Apply cadence, synchronize with cross-domain planning using SAFe, Decentralize decision-making- SAFe concept.
Manage scope and risks associated with 4 major quarterly and 8 monthly releases annually.
Evolve release and program management processes as the organization incorporates Agile software development tools and methodologies within IT.
Performed initial risk assessment and document risk mitigation plans and contingency procedures with the project team and maintain throughout life of the project.
Managed and optimized business processes using Six Sigma and Lean, including defining the KPIs .
Interact with cross functional teams to facilitate gathering of testing requirements.
Assist with weekly daily scrum meetings with offshore and onshore team.
Performed impact analysis during QA planning. Work with trading partners, clients, management, technical and non-technical personnel to create use cases and testing documentation.
Involved in automating test cases and creating automation framework.
Training and Agile coaching  to team on how to use Agile/Scrum practices and values, implemented Agile methodology throughout QA process.
Conducted test planning, chose test strategy, coverage and acceptance criteria.
Created RACI to align team on responsibilities - improving overall testing process.
Writing test cases based on the requirements, Designed and developed test cases in ALM, Rally as well as MS Excel. Use TDD, Continuous integration and testing methods.
Created automated test script using Selenium for regressing testing.
Developed test execution sequences, Manually performed Integration, Functional and Regression Testing.
Executed manual test cases for releases , Performed basic backend testing (SQL), Reported defects via Rally.
Contribute in test planning, test estimation, test design, executed manual test cases for releases in ALM & Rally.
Performed basic backend testing (SQL), Developed and tracked test productivity metrics.
Collaborated with stakeholders, Participate in agile scrum meeting and everyday meetings.
Run regression test scripts via Selenium Webdriver, TestNG, Maven tools.

HP (Hewlett Packard), TX, USA/ Kforce - Feb 2015 to Sep 2015
Scrum Master / QA Project Manager – Agile/Scrum/PM/QA - MD3 – Master Data Control Point (MDCP)
Role and Responsibilities:
Driving Agile Scrum principles, values, behaviors and methodologies throughout the organization.
Assisting teams with planning and execution of ceremonies, use of selected standard Agile tracking tool, User Story development.
Used TFS as the tool to Backlog tracking, burn-down metrics, velocity, and task management.
Ensured a common understanding by setting expectations in accordance with the Scrum principles, to align the stakeholders and team members.
Following all the SCRUM activities like Estimation, Sprint Demo, and Retrospective.
Ensured product backlog management and stories prioritization for consistent delivery.
Coach teams and management towards improving Agile process and metrics.
Partnering with the Product Owner in keeping the Backlog groomed.
Partnering with the Scrum Master to ensure cross-team coordination.
Identifying and maintaining relevant metrics that give the team insight into how they are doing and reporting these metrics to management.
Encouraging adoption of a truly Agile mindset, including ownership, self-management and empowerment.
Managing overall operations for executing projects involving scoping, design & sourcing.
Create Backlog and prioritize the user stories based on their business value.
Report team progress by burn-down charts and by conducting Sprint demos.
Record sprint metrics related to planned and completed story points, test cases, and bugs resolved.
Follow Agile best practices by conducting backlog grooming sessions, Sprint planning, and Sprint retrospectives with the development team.
Source code and version control management with Subversion(SVN).
Monitoring / tracking projects with respect to budgeted cost, demand forecasts, time over-runs to ensure timely execution of projects.
Addressing all the important issues & defining best practices for project support and documentation.
Mentoring and training project members to enable them to perform their activities effectively.
Performing project estimation, project scheduling and project costing.
Steering Delivery Management for technical deliverables of concurrent projects.
Analyzing user requirements and designing testing specifications.
Developing test plans, test cases and testing strategies for Business Intelligence (“BI”) development projects;
Analyzing and validating data quality, Creating Unit and Systems integrations test cases.
Providing guidance on the development of application using SQL and SOAP UI.
Analyzing test results and recommending modifications to the data warehouses to meet project specifications.
Oversight of  Risk Management and Mitigation planning for medium sized projects.
Monitored networks and Departmental KPI's for Risk Assessment, based on usage, and consumption.
Participating in the deployment of applications into the data warehouses from a quality assurance perspective.
Documenting the test plans, testing status and testing outcomes as required by the project, provide Daily, Weekly, Monthly status reports to stakeholders.
Strong experience in Onsite-Offshore working model (15+ team members), flexible, self-drive to identify process improvements and strong negotiation skill to implement the changes from QA front.
Tools used HP Agile Manager, SQL Developer, SoapUI 5.1.3, ALM 12.01, ETL - IDD, Batch Data Loader tools and Web Services are being used for MD3 Project.

PROJECT ONE: Walgreen Corporation, IL, USA - Mar 2014 to Feb 2015
Associate Consultant(QA Manager, Scrum Master) – Agile/Scrum/PM/QA - Community Management Systems and Customer Systems , Tata Consultancy Services (TCS) - From June 2010 to Feb 2015
Role and Responsibilities:
Worked at onsite location for Onshore-Offshore model and led mid size teams (4-10 associates) for various eCommerce web applications under CMS Portfolio.
Analyzed and reviewed functional overall design, technical overall designs and technical detailed design documents. Prepare Estimation of testing effort, Prepare Test Plan and Test Strategies with different approaches.
Test Case creation, Test Case execution in ALM, Test Summary report preparation by managing the schedule and meet deadlines.
The accountability for resources including people, budgets, systems, knowledge and experience.
Analyse more complex problems and propose a range of options with an informed and considered recommendation of the most appropriate solution.
Creating the project test plan and working with the development team to create Unit and Systems integration test cases.
Used TFS as the tool to Backlog tracking, burn-down metrics, velocity, and task management.
Ensured a common understanding by setting expectations in accordance with the Scrum principles, to align the stakeholders Worked as SCRUM Master to follow complete agile activities.
Took various Agile team training at to promote Agile and end to end Agile Implementation.
Coach and training stake holders on Agile by conducting workshops to ensure smooth functionality.
Ensured compliance of development team with Scrum methodology in delivering incremental features and monitor defined process adherence.
Coached/Mentored resources at different level, Prepare scope of sprint cycles and prioritize backlog.
Assist in migration from waterfall to agile methodologies, Perform Cost benefit analysis and ROI assessments, forecasting.
Develop templates of sprint cycles, work with users and stakeholders to finalize acceptance criteria and align with release calendar.
Demonstrate and validate sprints and sprint retrospection, Conducting Sprint Demo and Sprint Retrospective.
Handled project issues like staff management, scope creep and Track PV, EV, AC, EAC and variance etc .
Created automated excel and sharepoint application for Project management matrices.
Communicate with the stakeholders on a regular basis to provide feedback on Implementation progress of the solutions, involve the architect team in case of technical roadblock and Helping for technical solutions.
Ensured product backlog management and stories prioritization for consistent delivery.
Expert knowledge of various Agile methodologies. Hands-on admin experience using latest, industry-leading enterprise Agile Tools like MS Project, Jira, Kanban.
Drive execution of Unit and Systems Integration testing, following the complete defect life cycle including JIRA. Involved in monitoring the defects and assign issues to the development team, validate data quality with test metrics and providing test status summary on completion the testing.
Organize the kick-off, daily and weekly status meetings and send the Status Report to the Client.
Manages change in programme direction, scope, benefits, costs, and timing while minimising financial risks.
SQL Developer, PuTTY, WinSCP, SoapUI 4.6.3, HP UFT, ALM 11.5 tools and Batch processes are being used for CS and CMS portfolios.

PROJECT TWO:
Sears Holdings Corporation, MI, USA - June 2012 to March 2014
Associate Consultant /QA Project Lead – Agile/Scrum/PM/QA , Kmart Point of Sale
Tata Consultancy Services - From June 2010 to Feb 2015
Role and Responsibilities:
Worked as Onsite Design and Execution Lead for 15 members team.
Organize the testing kick-off meetings being a release coordinator.
Understand the testing effort by analyzing the requirements of project.
Developing test strategies and meeting project deadlines.
Keep track of the new requirements or change in requirements of the Project.
Organize the daily and weekly status meetings and send the Status Report to the Client.
Attend the regular client call and discuss the weekly status with the client.
Act as the single point of contact between Development and Testers and Communication with the Client as per requirements.
Track and prepare the report of testing activities like test evaluation summary report, test case coverage.

# Preprocessing

In [8]:
df

,filename,text,ID
0,Abiral_Pandey_Fullstack_Java.docx,Name: Abiral Pandey\nEmail: abiral.pandey88@gm...,1
1,Achyuth Resume_8.docx,Achyuth\n540-999-8048\nachyuth.java88@gmail.co...,2
2,Adelina_Erimia_PMP1.docx,"Adelina Erimia, PMP, Six Sigma Green Belt, SMC...",3
3,Adhi Gopalam - SM.docx,Adhi Gopalam\nadhigopalam@gmail.com\n281-212-3...,4
4,AjayKumar.docx,Ajay Kumar (CSM)\t \t\t Email/Skype: a...,5
...,...,...,...
219,Vishnu Java dev.docx,VISHNU J\nEmail to jammigumpulavishnu452@gmail...,220
220,Vivek Joshi_CV.docx,"\nVivek Joshi\nBusiness Analyst\nBellevue, WA\...",221
221,Vivek.BSA.docx,VIVEK SAGAR ...,222
222,Yohan BSA.docx,"YOHAN \nSr. Business Analyst\n\nVersatile, eff...",223
223,Yugesh_Resume.docx,Yugesh\n+1(515)-650-2459\nyugeshm4@gmail.com\n...,224

In [9]:
# Drop missing values
df.dropna(inplace=True)

In [10]:
import re
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

def clean_text(text):
    text = text.lower()                          # 1. lowercase
    text = re.sub(r'[^a-zA-Z\s]', '', text)     # 2. hapus karakter aneh
    text = re.sub(r'\s+', ' ', text).strip()     # 3. hapus whitespace berlebih
    text = " ".join(word for word in text.split() 
                    if word not in stop_words)    # 4. hapus stopwords
    return text

df["text_clean"] = df["text"].apply(clean_text)

In [11]:
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\grace\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\grace\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\grace\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\grace\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [14]:
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

def lemmatize_text(text):
    lemmatizer = WordNetLemmatizer()
    words = word_tokenize(text)
    lemmatized_words = [lemmatizer.lemmatize(word) for word in words]
    return " ".join(lemmatized_words)

lemmatized_texts = []
for text in df["text_clean"]:
    if not isinstance(text, str) or text == "":
        lemmatized_texts.append("")
        continue
    result = lemmatize_text(text) 
    lemmatized_texts.append(result)

df["text_lemmatized"] = lemmatized_texts

print("CLEAN     :", df["text_clean"][0][:500])
print("LEMMATIZED:", df["text_lemmatized"][0][:500])

CLEAN     : name abiral pandey email abiralpandeygmailcom phone current location woonsocket rhode island visa status us citizen summary dynamic individual years software development experience design development deployment maintenance production support web based clientserver business applications using oop javajee technologies exposure phases software development life cyclesdlc using agile rup waterfall designed developed web ui screen using angularjs developed angularjs controllers services filters direct
LEMMATIZED: name abiral pandey email abiralpandeygmailcom phone current location woonsocket rhode island visa status u citizen summary dynamic individual year software development experience design development deployment maintenance production support web based clientserver business application using oop javajee technology exposure phase software development life cyclesdlc using agile rup waterfall designed developed web ui screen using angularjs developed angularjs controller service filter directive vario

# TF-IDF

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(df["text_lemmatized"])
print(tfidf_matrix.shape)

(221, 15193)

# Rank: Cosine Similarity

In [22]:
from sklearn.metrics.pairwise import cosine_similarity

def rank_system (job_description, df, tfidf_matrix, vectorizer, top_n=10):
    job_description = clean_text(job_description)
    job_desc_lemma = lemmatize_text(job_description)
    job_vec = vectorizer.transform([job_desc_lemma])

    #hitung cosine similarity

    score = cosine_similarity(job_vec, tfidf_matrix)[0]
    df["score"] = score
    ranked_df = df.sort_values(by="score", ascending=False).head(top_n)
    return ranked_df[["ID", "filename", "score"]]

In [33]:
job_desc = pd.read_csv("job_title_des.csv")["Job Description"]
job_desc

0       We are looking for hire experts flutter develo...
1       PYTHON/DJANGO (Developer/Lead) - Job Code(PDJ ...
2       Data Scientist (Contractor)\n\nBangalore, IN\n...
3       JOB DESCRIPTION:\n\nStrong framework outside o...
4       job responsibility full stack engineer – react...
                              ...
2272    Job Summary\nPublished on : 26 days ago\nVacan...
2273    business entity cisco umbrella focus cloud-bas...
2274    Urgently reqd in a college in Mohali\nNetwork ...
2275    Key Responsibilities: Team leads for small or ...
2276    leslie hindman auctioneer one nation 's leadin...
Name: Job Description, Length: 2277, dtype: object

In [38]:
result = []

for idx, desc in enumerate(job_desc.iloc[:50]):
    print(f"\n\n=== Job Description {idx+1} ===")
    ranked_resumes = rank_system(desc, df, tfidf_matrix, vectorizer)
    print(ranked_resumes)

    top_resume = ranked_resumes.iloc[0]  

    result.append({
        "job_description": desc,
        "top_resume": top_resume["filename"],   
        "score": top_resume["score"]         
    })

final = pd.DataFrame(result)

=== Job Description 1 ===
      ID                 filename     score
23    24        BA - Navneet.docx  0.054083
129  130         ram krishna.docx  0.052439
9     10            Ami Jape.docx  0.045879
209  210           Venkat_BA.docx  0.043006
31    32  Brahma-Resume (BA).docx  0.041761
191  192     Syed_Zia_Ashraf.docx  0.038710
4      5           AjayKumar.docx  0.037176
131  132     Ramachandra EDA.docx  0.036215
96    97      Nandini_Resume.docx  0.035714
13    14         AnilAgarwal.docx  0.035293


=== Job Description 2 ===
      ID                             filename     score
198  199                    Tushar Patel.docx  0.141060
158  159  Sai Srinivas_Sr_Java_Developer.docx  0.139591
123  124                         Priya B.docx  0.139304
177  178             Siddhartha Gandroju.docx  0.133955
60    61                          jeck P.docx  0.132466
207  208                      vema reddy.docx  0.132268
168  169                    Satish Uduta.docx  0.130422
85    86                   Manohar Reddy.docx  0.129407
157  158                       Sai kumar.docx  0.125700
211  212                   Vijay Bhargav.docx  0.122962


=== Job Description 3 ===
      ID                             filename     score
211  212                   Vijay Bhargav.docx  0.164127
85    86                   Manohar Reddy.docx  0.127605
207  208                      vema reddy.docx  0.126875
158  159  Sai Srinivas_Sr_Java_Developer.docx  0.120217
64    65          Kashyap K. Vora resume.docx  0.116272
83    84                     Mani_Hadoop.docx  0.114449
174  175                    Shelly Woods.docx  0.113719
186  187       Srivatsan_Project_Manager.docx  0.111540
177  178             Siddhartha Gandroju.docx  0.106063
101  102            Naveen Kumar Bandela.docx  0.105170


=== Job Description 4 ===
      ID                             filename     score
95    96                       Mounika_P.docx  0.156754
198  199                    Tushar Patel.docx  0.153633
73    74                       Kumar Raj.docx  0.151034
33    34                     Chandler_BA.docx  0.150676
177  178             Siddhartha Gandroju.docx  0.129124
207  208                      vema reddy.docx  0.124046
158  159  Sai Srinivas_Sr_Java_Developer.docx  0.121820
123  124                         Priya B.docx  0.120001
163  164                    sanjay kumar.docx  0.118862
47    48                            Gopi.docx  0.116319


=== Job Description 5 ===
      ID                             filename     score
177  178             Siddhartha Gandroju.docx  0.190629
52    53                        harish S.docx  0.178214
95    96                       Mounika_P.docx  0.175911
103  104                 Navneeth Resume.docx  0.170822
186  187       Srivatsan_Project_Manager.docx  0.169107
85    86                   Manohar Reddy.docx  0.168917
158  159  Sai Srinivas_Sr_Java_Developer.docx  0.168874
106  107                    Nikith Reddy.docx  0.167735
165  166                        Sarath M.docx  0.167471
200  201                Ujvala BA Feb 20.docx  0.166327


=== Job Description 6 ===
      ID                        filename     score
186  187  Srivatsan_Project_Manager.docx  0.190569
182  183              Sravani Battu.docx  0.182535
214  215               Vikash_BA_Ab.docx  0.182120
4      5                  AjayKumar.docx  0.179526
103  104            Navneeth Resume.docx  0.175624
177  178        Siddhartha Gandroju.docx  0.174800
153  154            Sahas BA Resume.docx  0.173923
207  208                 vema reddy.docx  0.172981
49    50                 Haarika_BA.docx  0.169408
107  108            Nikki_Nimmagadd.docx  0.168213


=== Job Description 7 ===
      ID                             filename     score
177  178             Siddhartha Gandroju.docx  0.152035
158  159  Sai Srinivas_Sr_Java_Developer.docx  0.146406
167  168                    Satish Reddy.docx  0.145648
101  102            Naveen Kumar Bandela.docx  0.144662
85    86                   Manohar Reddy.docx  0.141712
73    74                       Kumar Raj.docx  0.141393
58    59                    Jaya prakash.docx  0.138410
200  201                Ujvala BA Feb 20.docx  0.136004
166  167                   SaravanaKumar.docx  0.135410
207  208                      vema reddy.docx  0.135059


=== Job Description 8 ===
      ID                                    filename     score
158  159         Sai Srinivas_Sr_Java_Developer.docx  0.138336
110  111                       nithin katapally.docx  0.127706
111  112                           nithin Reddy.docx  0.123681
101  102                   Naveen Kumar Bandela.docx  0.122891
85    86                          Manohar Reddy.docx  0.122387
172  173                           Sharath Java.docx  0.120678
66    67                            komal patel.docx  0.120640
115  116  Pavan Kumar Full Stack Java Developer.docx  0.119091
207  208                             vema reddy.docx  0.119038
177  178                    Siddhartha Gandroju.docx  0.117244


=== Job Description 9 ===
      ID                             filename     score
195  196                           Tarun.docx  0.205458
140  141   RaviBurra_Certified PM_DevOps.docx  0.191990
105  106                          Nikhil.docx  0.167421
103  104                 Navneeth Resume.docx  0.158529
85    86                   Manohar Reddy.docx  0.158449
73    74                       Kumar Raj.docx  0.156093
123  124                         Priya B.docx  0.155262
143  144             Reddemma_Lankipalle.docx  0.154380
177  178             Siddhartha Gandroju.docx  0.151776
158  159  Sai Srinivas_Sr_Java_Developer.docx  0.147337


=== Job Description 10 ===
      ID                        filename     score
186  187  Srivatsan_Project_Manager.docx  0.162402
103  104            Navneeth Resume.docx  0.157283
216  217                  Vishal S..docx  0.151530
220  221             Vivek Joshi_CV.docx  0.150027
177  178        Siddhartha Gandroju.docx  0.142485
207  208                 vema reddy.docx  0.142010
113  114                 Pankaj BSA.docx  0.141824
195  196                      Tarun.docx  0.136037
73    74                  Kumar Raj.docx  0.134896
182  183              Sravani Battu.docx  0.134821


=== Job Description 11 ===
      ID                        filename     score
186  187  Srivatsan_Project_Manager.docx  0.126547
216  217                  Vishal S..docx  0.107748
214  215               Vikash_BA_Ab.docx  0.107502
39    40                 Deepika DC.docx  0.106029
164  165         Santosh Arugula BA.docx  0.106026
112  113   Othman - Project Manager.docx  0.102843
87    88                      Mehul.docx  0.100279
113  114                 Pankaj BSA.docx  0.098970
103  104            Navneeth Resume.docx  0.098075
32    33     Business Analyst_GHyma.docx  0.098008


=== Job Description 12 ===
      ID                     filename     score
105  106                  Nikhil.docx  0.128497
207  208              vema reddy.docx  0.128297
85    86           Manohar Reddy.docx  0.126530
184  185                Sri Gati.docx  0.124685
177  178     Siddhartha Gandroju.docx  0.120340
223  224           Yugesh_Resume.docx  0.116750
109  110  Niteesh Java Developer.docx  0.115291
211  212           Vijay Bhargav.docx  0.114481
130  131            ram nandyala.docx  0.112046
167  168            Satish Reddy.docx  0.111005


=== Job Description 13 ===
      ID                        filename     score
64    65     Kashyap K. Vora resume.docx  0.149359
207  208                 vema reddy.docx  0.118444
211  212              Vijay Bhargav.docx  0.112136
85    86              Manohar Reddy.docx  0.112029
221  222                  Vivek.BSA.docx  0.109389
186  187  Srivatsan_Project_Manager.docx  0.108742
197  198             Tejaswi-resume.docx  0.106478
177  178        Siddhartha Gandroju.docx  0.103512
82    83        manish_singh_resume.docx  0.102500
192  193       Tanmay_Dam_Resume_BA.docx  0.101543


=== Job Description 14 ===
      ID                        filename     score
186  187  Srivatsan_Project_Manager.docx  0.241772
103  104            Navneeth Resume.docx  0.220167
4      5                  AjayKumar.docx  0.210807
24    25                   BA Kiran.docx  0.207377
113  114                 Pankaj BSA.docx  0.205863
214  215               Vikash_BA_Ab.docx  0.199798
49    50                 Haarika_BA.docx  0.197853
153  154            Sahas BA Resume.docx  0.193147
9     10                   Ami Jape.docx  0.190569
70    71            Krishnapriya_BA.docx  0.190323


=== Job Description 15 ===
      ID                                  filename     score
220  221                       Vivek Joshi_CV.docx  0.150579
4      5                            AjayKumar.docx  0.141759
100  101                         Naveen Arora.docx  0.122938
80    81                 Mahesh_Kamath_PM (1).docx  0.122425
186  187            Srivatsan_Project_Manager.docx  0.120537
135  136  Ranjan_Project Manager-Scrum Master.docx  0.116000
216  217                            Vishal S..docx  0.114362
23    24                         BA - Navneet.docx  0.114269
201  202                     Utthan Silawal12.docx  0.114220
200  201                     Ujvala BA Feb 20.docx  0.114210


=== Job Description 16 ===
      ID                         filename     score
32    33      Business Analyst_GHyma.docx  0.124828
182  183               Sravani Battu.docx  0.120468
93    94  Mounika health care resume.docx  0.114951
200  201            Ujvala BA Feb 20.docx  0.114286
164  165          Santosh Arugula BA.docx  0.107954
76    77               Madhuri Pawar.docx  0.107472
92    93         mounika BA resume 7.docx  0.106917
49    50                  Haarika_BA.docx  0.105861
186  187   Srivatsan_Project_Manager.docx  0.105748
74    75             Kuppurajbabu_BA.docx  0.105090


=== Job Description 17 ===
      ID                        filename     score
148  149            Resume2018March.docx  0.206297
186  187  Srivatsan_Project_Manager.docx  0.137222
91    92                   mohid_rj.docx  0.131175
127  128                   Rajesh_k.docx  0.130045
108  109    Nilesh-resume_1_phplead.docx  0.129136
70    71            Krishnapriya_BA.docx  0.127832
208  209   Venkata_Sr.PHP_Developer.docx  0.127544
191  192            Syed_Zia_Ashraf.docx  0.125944
52    53                   harish S.docx  0.125417
50    51                Harika_java.docx  0.124829


=== Job Description 18 ===
      ID                            filename     score
33    34                    Chandler_BA.docx  0.102755
95    96                      Mounika_P.docx  0.091719
168  169                   Satish Uduta.docx  0.079716
73    74                      Kumar Raj.docx  0.077073
207  208                     vema reddy.docx  0.071605
161  162  Samir Naik-NJ - Feb 2018-V6.0.docx  0.069416
92    93            mounika BA resume 7.docx  0.069024
162  163  Samir Naik-NJ - Mar 2018-V3.0.docx  0.068498
13    14                    AnilAgarwal.docx  0.065949
67    68              Komala BSA Resume.docx  0.064857


=== Job Description 19 ===
      ID                                    filename     score
39    40                             Deepika DC.docx  0.291993
186  187              Srivatsan_Project_Manager.docx  0.270644
103  104                        Navneeth Resume.docx  0.250993
4      5                              AjayKumar.docx  0.221510
38    39                   Deepika Chintalapati.docx  0.217472
26    27  Balaji Gopalakrishnan Project Manager.docx  0.215589
97    98                           Naren Sr.BA .docx  0.214204
216  217                              Vishal S..docx  0.213666
98    99                            Naren Sr.BA.docx  0.213510
220  221                         Vivek Joshi_CV.docx  0.209494


=== Job Description 20 ===
      ID                            filename     score
105  106                         Nikhil.docx  0.197385
196  197                Tarun_Developer.docx  0.171448
177  178            Siddhartha Gandroju.docx  0.168422
216  217                      Vishal S..docx  0.166182
73    74                      Kumar Raj.docx  0.163901
195  196                          Tarun.docx  0.163183
186  187      Srivatsan_Project_Manager.docx  0.162038
140  141  RaviBurra_Certified PM_DevOps.docx  0.161936
12    13      Anil Krishna Mogalaturthi.docx  0.158223
123  124                        Priya B.docx  0.157809


=== Job Description 21 ===
      ID                        filename     score
39    40                 Deepika DC.docx  0.187150
8      9                Amar Sr BSA.docx  0.165711
38    39       Deepika Chintalapati.docx  0.145870
97    98               Naren Sr.BA .docx  0.121785
98    99                Naren Sr.BA.docx  0.120408
156  157             Sai Krishna BA.docx  0.119190
67    68          Komala BSA Resume.docx  0.118138
200  201           Ujvala BA Feb 20.docx  0.117219
186  187  Srivatsan_Project_Manager.docx  0.116682
153  154            Sahas BA Resume.docx  0.116021


=== Job Description 22 ===
      ID                       filename     score
148  149           Resume2018March.docx  0.439329
108  109   Nilesh-resume_1_phplead.docx  0.163731
127  128                  Rajesh_k.docx  0.117402
157  158                 Sai kumar.docx  0.113692
208  209  Venkata_Sr.PHP_Developer.docx  0.112275
37    38                      Dave.docx  0.103014
40    41                     Derik.docx  0.103014
202  203                 V Ashok A.docx  0.093834
117  118               Pierre John.docx  0.092293
13    14               AnilAgarwal.docx  0.092229


=== Job Description 23 ===
      ID                            filename     score
4      5                      AjayKumar.docx  0.196667
103  104                Navneeth Resume.docx  0.188763
15    16           Ashok Jayakumar - PM.docx  0.185446
220  221                 Vivek Joshi_CV.docx  0.176039
140  141  RaviBurra_Certified PM_DevOps.docx  0.174817
186  187      Srivatsan_Project_Manager.docx  0.173787
3      4              Adhi Gopalam - SM.docx  0.172162
9     10                       Ami Jape.docx  0.168003
171  172                  Shaker Resume.docx  0.165853
67    68              Komala BSA Resume.docx  0.164643


=== Job Description 24 ===
      ID                           filename     score
216  217                     Vishal S..docx  0.223522
186  187     Srivatsan_Project_Manager.docx  0.200434
112  113      Othman - Project Manager.docx  0.191826
164  165            Santosh Arugula BA.docx  0.191722
32    33        Business Analyst_GHyma.docx  0.181406
23    24                  BA - Navneet.docx  0.178538
170  171  Shail_Tank-Business Analyst .docx  0.173834
209  210                     Venkat_BA.docx  0.170416
200  201              Ujvala BA Feb 20.docx  0.169846
153  154               Sahas BA Resume.docx  0.167182


=== Job Description 25 ===
      ID                             filename     score
208  209        Venkata_Sr.PHP_Developer.docx  0.221044
127  128                        Rajesh_k.docx  0.192816
108  109         Nilesh-resume_1_phplead.docx  0.154585
148  149                 Resume2018March.docx  0.120117
52    53                        harish S.docx  0.096823
33    34                     Chandler_BA.docx  0.094733
73    74                       Kumar Raj.docx  0.090025
158  159  Sai Srinivas_Sr_Java_Developer.docx  0.086867
177  178             Siddhartha Gandroju.docx  0.080165
101  102            Naveen Kumar Bandela.docx  0.078356


=== Job Description 26 ===
      ID                  filename     score
198  199         Tushar Patel.docx  0.150648
73    74            Kumar Raj.docx  0.147218
105  106               Nikhil.docx  0.145625
187  188       Sudhakar Reddy.docx  0.145182
177  178  Siddhartha Gandroju.docx  0.144562
95    96            Mounika_P.docx  0.141260
157  158            Sai kumar.docx  0.140996
163  164         sanjay kumar.docx  0.139535
91    92             mohid_rj.docx  0.136866
33    34          Chandler_BA.docx  0.135012


=== Job Description 27 ===
      ID                           filename     score
57    58               Jagan S Iyer PM.docx  0.085375
119  120                      Pranay P.docx  0.084440
207  208                    vema reddy.docx  0.081179
188  189  Sumanth Manne Java Developer.docx  0.080854
74    75               Kuppurajbabu_BA.docx  0.079315
123  124                       Priya B.docx  0.077637
32    33        Business Analyst_GHyma.docx  0.077210
177  178           Siddhartha Gandroju.docx  0.077202
105  106                        Nikhil.docx  0.075787
16    17        Ashwini J2EE Developer.docx  0.075562


=== Job Description 28 ===
      ID                           filename     score
177  178           Siddhartha Gandroju.docx  0.180610
85    86                 Manohar Reddy.docx  0.172194
207  208                    vema reddy.docx  0.168231
16    17        Ashwini J2EE Developer.docx  0.167626
141  142         ravikiran JALASUTRAPU.docx  0.166961
159  160               sairithvik alla.docx  0.166912
183  184          Sravani Singirikonda.docx  0.165371
188  189  Sumanth Manne Java Developer.docx  0.164124
77    78                     madhuri R.docx  0.163536
211  212                 Vijay Bhargav.docx  0.162028


=== Job Description 29 ===
      ID                            filename     score
105  106                         Nikhil.docx  0.223683
121  122                      Praveen B.docx  0.207989
216  217                      Vishal S..docx  0.195684
186  187      Srivatsan_Project_Manager.docx  0.171400
103  104                Navneeth Resume.docx  0.165623
140  141  RaviBurra_Certified PM_DevOps.docx  0.161513
12    13      Anil Krishna Mogalaturthi.docx  0.161152
177  178            Siddhartha Gandroju.docx  0.156779
185  186                     srinivas b.docx  0.152534
139  140                     Ravi Reddy.docx  0.152302


=== Job Description 30 ===
      ID                             filename     score
103  104                 Navneeth Resume.docx  0.175059
177  178             Siddhartha Gandroju.docx  0.170221
95    96                       Mounika_P.docx  0.169851
105  106                          Nikhil.docx  0.167566
91    92                        mohid_rj.docx  0.167377
4      5                       AjayKumar.docx  0.165791
158  159  Sai Srinivas_Sr_Java_Developer.docx  0.164731
168  169                    Satish Uduta.docx  0.163973
9     10                        Ami Jape.docx  0.160557
99   100                        Naresh V.docx  0.158362


=== Job Description 31 ===
      ID                        filename     score
186  187  Srivatsan_Project_Manager.docx  0.128375
83    84                Mani_Hadoop.docx  0.128174
64    65     Kashyap K. Vora resume.docx  0.116642
25    26                BA with INV.docx  0.115205
9     10                   Ami Jape.docx  0.111282
113  114                 Pankaj BSA.docx  0.109565
211  212              Vijay Bhargav.docx  0.109490
174  175               Shelly Woods.docx  0.109042
191  192            Syed_Zia_Ashraf.docx  0.105383
103  104            Navneeth Resume.docx  0.104688


=== Job Description 32 ===
      ID                             filename     score
208  209        Venkata_Sr.PHP_Developer.docx  0.403369
127  128                        Rajesh_k.docx  0.300070
52    53                        harish S.docx  0.186266
33    34                     Chandler_BA.docx  0.134519
50    51                     Harika_java.docx  0.121905
158  159  Sai Srinivas_Sr_Java_Developer.docx  0.121327
108  109         Nilesh-resume_1_phplead.docx  0.118536
177  178             Siddhartha Gandroju.docx  0.115832
202  203                       V Ashok A.docx  0.115796
73    74                       Kumar Raj.docx  0.115593


=== Job Description 33 ===
      ID                             filename     score
208  209        Venkata_Sr.PHP_Developer.docx  0.223777

In [39]:
final

,job_description,top_resume,score
0,We are looking for hire experts flutter develo...,BA - Navneet.docx,0.054083
1,PYTHON/DJANGO (Developer/Lead) - Job Code(PDJ ...,Tushar Patel.docx,0.141060
2,"Data Scientist (Contractor)\n\nBangalore, IN\n...",Vijay Bhargav.docx,0.164127
3,JOB DESCRIPTION:\n\nStrong framework outside o...,Mounika_P.docx,0.156754
4,job responsibility full stack engineer – react...,Siddhartha Gandroju.docx,0.190629
5,Software Developer - Integration*\nImmediate O...,Srivatsan_Project_Manager.docx,0.190569
6,senior full stack developer \- 1800026h cwt lo...,Siddhartha Gandroju.docx,0.152035
7,"Job Description:\n\nReactJS + NodeJs, Azure Fu...",Sai Srinivas_Sr_Java_Developer.docx,0.138336
8,Main Responsibilities and Deliverables:\nManag...,Tarun.docx,0.205458
9,"Overview\n\n\nBased in Silicon Valley, Tintri ...",Srivatsan_Project_Manager.docx,0.162402
10,richardsontexasunited state bausp4 boeing comp...,Srivatsan_Project_Manager.docx,0.126547
11,"Remote, Any where\n2 - 4 years\n₹8L - ₹12L / y...",Nikhil.docx,0.128497
12,"Excited by Big Data, Machine Learning and Pred...",Kashyap K. Vora resume.docx,0.149359
13,As a member of our Software Engineering Group ...,Srivatsan_Project_Manager.docx,0.241772
14,JOB DESCRIPTION\n\nJob Title: Software Enginee...,Vivek Joshi_CV.docx,0.150579
15,Overview:\n\nWestern National is seeking a hig...,Business Analyst_GHyma.docx,0.124828
16,Experience: 2-5 years\n\nJob Location:- Aurang...,Resume2018March.docx,0.206297
17,Job Code : ID190704\n\nJob Description:\nExper...,Chandler_BA.docx,0.102755
18,job description summary highly skilled technic...,Deepika DC.docx,0.291993
19,Job Summary\n\nOur mission at Style Theory is ...,Nikhil.docx,0.197385
20,country place mortgage founded 1995 subsidiary...,Deepika DC.docx,0.187150
21,Position: WordPress Developer\nLocation: Prahl...,Resume2018March.docx,0.439329
22,MonetizeMore builds industry leading ad techno...,AjayKumar.docx,0.196667
23,qualification essential qualification related ...,Vishal S..docx,0.223522
24,Job Summary\n**\nWe are looking for Fresher PH...,Venkata_Sr.PHP_Developer.docx,0.221044
25,Job Responsibilities:\nDesign and build applic...,Tushar Patel.docx,0.150648
26,Software Developer\n\nWho we are:\nThe America...,Jagan S Iyer PM.docx,0.085375
27,Full Job Description\n\nCoordinating with deve...,Siddhartha Gandroju.docx,0.180610
28,Vidooly is looking for candidates with analyti...,Nikhil.docx,0.223683
29,"No relocation needed, can telework from home, ...",Navneeth Resume.docx,0.175059
30,Vista Equity Partners is the world's leading p...,Srivatsan_Project_Manager.docx,0.128375
31,Job Description:\n\n1-4 years of experience as...,Venkata_Sr.PHP_Developer.docx,0.403369
32,1 - 3 years experience\nFront-end skills: HTML...,Venkata_Sr.PHP_Developer.docx,0.223777
33,Staff Machine Learning Scientist\n\nHyderabad/...,Kashyap K. Vora resume.docx,0.113142
34,Summary of the Position:\n\nWe are seeking a B...,Siddhartha Gandroju.docx,0.218943
35,Mandatory skills: Kubernetes and docker\nExper...,Tarun.docx,0.178696
36,BE / BCA / any bachelor degree\nCertification:...,Praveen B.docx,0.269104
37,We are on the hunt for a Wordpress developer w...,Resume2018March.docx,0.408043
38,Job Duties:\nHardware and Software installatio...,Praveen B.docx,0.174401
39,Job Description\n\nWe are looking for a PHP De...,Venkata_Sr.PHP_Developer.docx,0.298130
40,Nokia is a global leader in the technologies t...,Priya B.docx,0.154040
41,If you are a current Motorola Solutions employ...,Sahas BA Resume.docx,0.118653
42,We are seeking talented and creative individua...,AjayKumar.docx,0.214568
43,Greetings of the day!!!!\n\nPosition- WordPres...,Resume2018March.docx,0.287555
44,Job Description\n3+ years’ experience working ...,Siddhartha Gandroju.docx,0.261427
45,We are looking for Experienced & well knowledg...,Mounika_P.docx,0.125475
46,Company Description:\nHireXP is committed to b...,vema reddy.docx,0.149033
47,Requirements\n\nStrong background in Linux/Uni...,Priya B.docx,0.157763
48,We are looking for an iOS developer who posses...,Kumar Raj.docx,0.161655
49,Role Proficiency:Level of Proficiency:Independ...,AjayKumar.docx,0.252628